name: NodeJS with Webpack
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install
        npm run build
    
    - name: Git Commit and Push
      # You may pin to the exact commit or the version.
      # uses: github-actions-x/commit@5cf7985b07155682f82d02b6c2188d90cebeb0c8
      uses: github-actions-x/commit@v2.8
      with:
        github-token: $\{{ secrets.GITHUB_TOKEN }}
        push-branch: build
        commit-message: Updated dist
        files: dist
        force-add: true
        force-push: true
        email: gougeonvincent31@gmail.com
        name: Actions
